name: Validate Vision Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Validate Image Metadata
        continue-on-error: true
        run: >
            python -m pip install --force-reinstall ./vision &&
            python .github/workflows/validate_image_metadata.py

      - name: Validate Python Requirements
        run: .github/workflows/validate_requirements.sh
      